### ISSUE TITLE
window access

### ISSUE THREAD

**Issue by retorquere** [kennygomdori/AsyncIndexedDB#5]
I intend to use indexeddb in a worker where `window` is undefined. Is it necessary that this library uses `window` to access globals rather than just using them from the global scope implicitly?

**Comment by kennygomdori** [comment]
Thank you for raising the issue. No, it's completely unnecessary, and is a bad form.
I replaced it with `self`, so it would also work in workers.

**Comment by retorquere** [comment]
The files in `dist` still use `window`
